# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b472b23dc85bfa933ad0f7be26022aff615e90b18a385278590320900dfa11c9c30690516ca96f032d81e90a6da79b915ba0dc57467f46a5effed4bd0359abb

test:
  secret_key_base: eec92394d2c1c571185fb3d9c192f18d569c5494624e5f68dfd434b05642f4d6760787c0ba2244b2d38786f860a88c9b7fc2a992bca94871fa4121476dfadbfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
